resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: ory_gitlab_int
      path: orym2c/oryproject1

pipelines:
  - name: my_first_pipeline
    steps:
      - name: MavenWithArtifactoryBuild
        type: MvnBuild
        configuration:
          sourceLocation: .
          inputResources:
            - name: git_repo
          integrations:
            - name: ory_rt_integration
