resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: ory_gitlab_int
      path: orym2c/oryproject1

pipelines:
  - name: my_first_pipeline
    steps:
      - name: MavenWithArtifactoryBuild
        type: MvnBuild
        configuration:
          sourceLocation: ./complete
          forceXrayScan: true
          autoPublishBuildInfo: true
          resolverSnapshotRepo: default-maven-remote
          resolverReleaseRepo: default-maven-remote
          deployerSnapshotRepo: default-maven-local
          deployerReleaseRepo: default-maven-local
          inputResources:
            - name: git_repo
          outputResources:
            - name: mvn_build_info
          integrations:
            - name: ory_rt_integration

       
