valuesFilePath: ./pipelines.resources.yml

pipelines:
  - name: jfrog_pipeline
    steps:
      - name: MavenWithArtifactoryBuild
        type: MvnBuild
        configuration:
          sourceLocation: .
         
          inputResources:
            - name: git_repo
          integrations:
            - name: repositoryName
     
     
