resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: ory_gitlab_int
      path: orym2c/oryproject1

  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: ory_rt_integration
      buildName: SampleApp
      buildNumber: 1

pipelines:
  - name: my_first_pipeline
    steps:
      - name: MavenWithArtifactoryBuild
        type: MvnBuild
        configuration:
          sourceLocation: ./complete
          inputResources:
            - name: git_repo
          integrations:
            - name: ory_rt_integration


       
