template: true   # required for local templates
valuesFilePath: ./values.yml
 
resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitIntegration }}                     
      path: {{ .Values.gitRepositoryPath }}
      branches:
        include: master
 

       
 
pipelines:
  - name: MyMavenPipeline
    steps:
      - name: MavenWithAll
        type: MvnBuild
        configuration:
          integrations:
            - name: art
          inputResources:
            - name: mvn_repo
          outputResources:
            - name: mvn_build_info
          mvnCommand: clean install test
          sourceLocation: mvnproject
          resolverSnapshotRepo: snapshots-remote-maven
          resolverReleaseRepo: releases-remote-maven
          deployerSnapshotRepo: snapshots-local-maven
          deployerReleaseRepo: releases-local-maven
          forceXrayScan: true
          failOnScan: true
          autoPublishBuildInfo: true
