resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: ory_gitlab_int
      path: orym2c/oryproject1
​

pipelines:
  - name: jfrog_pipeline
    steps:
      - name: MavenWithArtifactoryBuild
        type: MvnBuild
        configuration:
          sourceLocation: .
         
          inputResources:
            - name: git_repo
          integrations:
            - name: repositoryName


     
     
